[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snakrrr"
version = "0.1.0"
description = "A minimal Python system info-fetcher that displays only essential information without bloat."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Sharpnesse49" }
]
dependencies = []

[project.urls]
Repository = "https://github.com/Sharpnesse49/Snakrrr"

[project.scripts]
snakrrr = "snakrrr.main:main"
